name: mlflow-ci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - xgboost=1.5.0
  - mlflow=1.25.0
  - numpy=1.20.3
  - sqlalchemy=1.4.46
  - setuptools=59.6.0
  - protobuf=3.20.3